### ISSUE TITLE
Add ansi-colors to helptext

### ISSUE THREAD

**Issue by gizmomogwai** [andrey-zherikov/argparse#11]
e.g. https://picocli.info/

**Comment by andrey-zherikov** [comment]
This would be nice enhancement but it's hard to implement it right now. I have plans to redesign help printer to be more flexible and less coupled with the rest of code so you can customize it the way you want. I also need to figure out what would be the best solution here as I don't want to add any dependency.

**Comment by gizmomogwai** [comment]
+1 for not adding a dependency. I think there is not too much customization needed ... one mode that prints with color (dont thing that the colors need to be adjustable), and one mode without colors (normally that is used as well for non tty output).

regarding colors a nice tutorial is: http://xn--rpa.cc/irl/term.html.

**Comment by gizmomogwai** [comment]
btw. congratulations for version 1.0.0!

**Comment by andrey-zherikov** [comment]
Thanks. I'm working on refactoring of help printer.

**Comment by gizmomogwai** [comment]
👍

**Comment by andrey-zherikov** [comment]
> regarding colors a nice tutorial is: http://xn--rpa.cc/irl/term.html.

Do you have another link? This one doesn't work for me: `xn--rpa.cc has expired`.

**Comment by andrey-zherikov** [comment]
I'm also curious about default coloring scheme. Is there a tool that prints help screen in color?

One of the possible solutions can be is just to add coloring support through new `titleColor`, `argNameColor` etc. parameters in `config` without any default coloring scheme.

**Comment by gizmomogwai** [comment]
A colleague used https://picocli.info/#_ansi_colors_and_styles in a project and that got me hooked on the colors. I think there is also a color crate for rusts clap.

**Comment by gizmomogwai** [comment]
I am not sure, that too much configurability is really required. Perhaps it also makes sense to not use real colors but only bold and underline and so on.

**Comment by gizmomogwai** [comment]
> > regarding colors a nice tutorial is: http://xn--rpa.cc/irl/term.html.
> 
> Do you have another link? This one doesn't work for me: `xn--rpa.cc has expired`.

I just saw yesterday that there is a problem! The link works with wayback machine.

**Comment by gizmomogwai** [comment]
> > > regarding colors a nice tutorial is: http://xn--rpa.cc/irl/term.html.
> > 
> > 
> > Do you have another link? This one doesn't work for me: `xn--rpa.cc has expired`.
> 
> I just saw yesterday that there is a problem! The link works with wayback machine.

https://web.archive.org/web/20220520031528/http://xn--rpa.cc/irl/term.html

**Comment by andrey-zherikov** [comment]
> I am not sure, that too much configurability is really required. Perhaps it also makes sense to not use real colors but only bold and underline and so on.

There is no implementation difference between colors and bold/italic/underscore - they all are ansi escape sequences. So our can be `titleStyle ` etc.

**Comment by andrey-zherikov** [comment]
Thanks for all links, I'll use them as examples

**Comment by gizmomogwai** [comment]
> > I am not sure, that too much configurability is really required. Perhaps it also makes sense to not use real colors but only bold and underline and so on.
> 
> There is no implementation difference between colors and bold/italic/underscore - they all are ansi escape sequences. So our can be `titleStyle ` etc.

exactly

**Comment by andrey-zherikov** [comment]
Also looking at [picocli](https://picocli.info/#_color_scheme), I think we should have styling settings for the following pieces in `Config`:
- name of program
- name of subcommand
- name of argument group (this will include "Available commands" title for subcommands)
- value placeholder of positional argument
- name of named argument
- value placeholder of named argument
- error text

**Comment by gizmomogwai** [comment]
I think your proposal is very well though through. Regarding the colors in the epilog and so on, one other idea could be to expose the decision argparse has taken for the coloring and forward that to the delegate (works only with the delegate though). Another (perhaps simple enough approach would be, to just not allow that ... e.g. if someone injects a \r at the moment into the description, there will also be problems). So I think it could be possible to recommend to not use colors in descriptions and so on and leave misuses / tunings up to the user.

**Comment by andrey-zherikov** [comment]
> if someone injects a \r at the moment into the description, there will also be problems

Not sure that I got this.

**Comment by andrey-zherikov** [comment]
I played a bit with user facing API for styling and I believe I found pretty good version (just a limited example):
```d
struct Style
{
    auto argumentGroupTitle = red.onWhite;
    auto namedArgumentName  = yellow.onCyan;
    auto namedArgumentValue = onMagenta.green;
}
```

I will limit styling to bold, italic, underline and 4-bit colors (ANSI codes 1, 3, 4, 30-37, 40-47, 90-97, 100-107) for now. If there is a demand, this can be extended.

**Comment by gizmomogwai** [comment]
Sounds very good to me. The api resembles also what I did in colored dub package! But for your lib it's best to not add a dependencY I think!

**Comment by andrey-zherikov** [comment]
I looked at few coloring packages including yours :-D
I'll add no dependency for sure.

**Comment by andrey-zherikov** [comment]
@gizmomogwai I created draft PR. Could you take a look once you have time?

**Comment by gizmomogwai** [comment]
Thats great news .. hope to have a look today or tomorrow.

**Comment by andrey-zherikov** [comment]
Unfortunately yes. I want to add coloring support to Epilog, Description etc. before making new release.

**Comment by gizmomogwai** [comment]
This was my last question... It still stands that you want to automatically remove coloring if its deactivated, right?

**Comment by andrey-zherikov** [comment]
There are two parts:
- remove coloring if it's deactivated
- correct calculation of text length in printing (need to re-implement std `wrap` function which is used right now)

**Comment by gizmomogwai** [comment]
thanks for showing me the wrap function :) might come in handy ... but makes sense to have something like that.

**Comment by andrey-zherikov** [comment]
FYI I had to implement [`wrapMutiLine`](https://github.com/andrey-zherikov/argparse/blob/master/source/argparse/help.d#L255) because std `wrap` doesn't respect `"\n"`

**Comment by gizmomogwai** [comment]
interesting .. on which column are your wrapping? i would have expected to not touch the epilog at all (besides removing ansi escape codes). might be worth a comment in the docs / api documentation.

**Comment by andrey-zherikov** [comment]
Wrapping is used to [print argument description](https://github.com/andrey-zherikov/argparse/blob/master/source/argparse/help.d#L111-L127) only. But I think supporting styling in epilog only and not in description will look incomplete.

> on which column are your wrapping

[80](https://github.com/andrey-zherikov/argparse/blob/master/source/argparse/help.d#L259)
