### ISSUE TITLE
`Param`s are non-assignable

### ISSUE THREAD

**Issue by SirNickolas** [andrey-zherikov/argparse#114]
`struct Param(VALUE_TYPE)` contains a `const Config* config`, which disables the assignment operator for the whole struct. Perhaps you meant `const(Config)* config`?

**Comment by SirNickolas** [comment]
Or even `immutable(Config)* config` to state the intent more precisely. Turning `const` into `immutable` is a backwards-compatible change.

**Comment by andrey-zherikov** [comment]
Although it can be made immutable I prefer not to do that - "const" allows more flexibility to change implementation if needed.
