### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by cyrusmsk** [andrey-zherikov/argparse#169]
Advanced sub-command example
with LDC: 1.38
macOS (m1) version 13.3.1 

Steps:
dub build
./app

Error:
core.exception.ArrayIndexError@../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/internal/command.d(67): index [0] is out of bounds for array of length 0

and a lot of other errors

**Comment by andrey-zherikov** [comment]
Thanks for reporting this! I'll take a look. 

Sorry for not responding earlier.

**Comment by cyrusmsk** [comment]
With version ~master it worked now. Thanks
