### ISSUE TITLE
Avoid polluting the main-thread stack with argparse internal context 

### ISSUE THREAD

**Issue by ljmf00-wekaio** [andrey-zherikov/argparse#170]
Regarding https://github.com/dlang/phobos/pull/8759#issuecomment-2274553876 

I can see this being a problem on big projects where stack is precious. Pretty much main is right now polluted with what can effectively be a global `__gshared` state.

**Comment by andrey-zherikov** [comment]
Am I right that the concern is about CLI.main which creates a lot of objects on stack?

**Comment by ljmf00-wekaio** [comment]
yes

**Comment by andrey-zherikov** [comment]
Looking at [`CLI.parseArgs`](https://github.com/andrey-zherikov/argparse/blob/release/1.x/source/argparse/api/cli.d#L65-L81) (which is called by [`CLI.main`](https://github.com/andrey-zherikov/argparse/blob/release/1.x/source/argparse/api/cli.d#L150)): function parameters can probably be on a stack (depending on calling convention) and the only object which is created on a stack by that function is `Result`. Are your concerns about `Result` or I missed something?

**Comment by ljmf00-wekaio** [comment]
I just realized there's this overload `static Result parseArgs(ref COMMAND receiver, string[] args)`. I was talking about `receiver` object, which is the "Options", the parsed object.

Maybe this is documented and I didn't see it.
