### ISSUE TITLE
Be able to have completion without requiring recompilation of another binary

### ISSUE THREAD

**Issue by ljmf00-wekaio** [andrey-zherikov/argparse#172]
Regarding https://github.com/dlang/phobos/pull/8759#issuecomment-2274553876 

Pretty self explanatory. Currently we need `--d-version=argparse_completion` to generate completion data.

**Comment by andrey-zherikov** [comment]
Do you want a single binary that parses the command line and "executes" it and also provides shell completion? In this case binary would need to distinguish between "execute" and "completion" modes.

**Comment by ljmf00-wekaio** [comment]
yes

**Comment by andrey-zherikov** [comment]
Brainstorming how this can be achieved... We need a run-time switch between "execution" and "completion" modes. IMO this can be done either through "magic" value in `argv[1]` or environment variable. First approach has a problem that whatever that "magic" value is, it can be a valid value for "execution" mode (for example, as a value for positional argument). The second approach, I think, is a way to go. The only thing is that we need to ensure that env variable name doesn't conflict with other variables in a program and this can be solved by allowing customization of variable name through `Config`.

**Comment by ljmf00-wekaio** [comment]
Why complicating where you could defer that choice to the user? If the user wants a specific flag, they will have it and call something like `printCompletionInfo`.

**Comment by ljmf00-wekaio** [comment]
Maybe that is enough :)
