### ISSUE TITLE
Error: template `SubCommand` is not defined

### ISSUE THREAD

**Issue by rempas** [andrey-zherikov/argparse#173]
I'm following the documentation page about [Subcommands](https://andrey-zherikov.github.io/argparse/subcommands.html) and when trying to run my code, I get the following error:

```
source/cmd_args/cmd_data.d(10,3): Error: template instance `SubCommand!(HelpMode, RunMode, Default!BuildMode)` template `SubCommand` is not defined, did you mean SubCommands?
source/app.d(5,1): Error: mixin `app.main!((args)
{
import std.stdio;
write("Args parsed!!!");
}
)` is not defined
```

Of course, I used `import argparse;` on every file, to be sure.

The example is run through Dub, using DMD version `v2.109.1`.

**Comment by andrey-zherikov** [comment]
Do you use argparse from master or the latest published version from dub?

**Comment by rempas** [comment]
> Do you use argparse from master or the latest published version from dub?

The latest published version from Dub.

**Comment by andrey-zherikov** [comment]
> The latest published version from Dub.

Current HEAD contains breaking changes compared to the latest published version. These changes include `Subcommand`.

You can find documentation for published version in [README](https://github.com/andrey-zherikov/argparse/blob/v1.3.0/README.md)

**Comment by rempas** [comment]
> > The latest published version from Dub.
> 
> Current HEAD contains breaking changes compared to the latest published version. These changes include `Subcommand`.
> 
> You can find documentation for published version in [README](https://github.com/andrey-zherikov/argparse/blob/v1.3.0/README.md)

Thanks for the information. I'm trying to use both [without UDA](https://github.com/andrey-zherikov/argparse/blob/v1.3.0/README.md#subcommands-without-uda) and, with [shared arguments](https://github.com/andrey-zherikov/argparse/blob/v1.3.0/README.md#subcommands-with-shared-common-arguments) and none of them works...

First case gives the following error:

```
source/cmd_args/parse_cmd_args.d(28,7): Error: template instance `CLI!(HelpMode, RunMode, BuildMode)` template `CLI` is not defined
source/cmd_args/parse_cmd_args.d(28,1): Error: mixin `cmd_args.parse_cmd_args.main!main_` is not defined
```

Second case gives the following error:

```
source/cmd_args/cmd_data.d(10,3): Error: template instance `SumType!(HelpMode, RunMode, BuildMode)` template `SumType` is not defined
source/cmd_args/parse_cmd_args.d(37,1): Error: mixin `cmd_args.parse_cmd_args.main!((prog)
{
static assert(is(typeof(prog) == CmdData));
int result = prog.cmd.match!((.HelpMode)
{
writeln("This is the help mode!");
}
, (.BuildMode)
{
writeln("This is the build mode!");
}
, (.RunMode)
{
writeln("This is the run mode!");
}
);
writeln("result = ", result);
return 0;
}
)` is not defined
```

**Comment by andrey-zherikov** [comment]
Could you share source code that I can use to reproduce these errors?

**Comment by andrey-zherikov** [comment]
Could you share source code that I can use to reproduce these errors?

**Comment by rempas** [comment]
> Could you share source code that I can use to reproduce these errors?

My pleasure! Look [here](https://codeberg.org/rempas/trying_argparse/src/branch/master/source)! Start with `source/app.d` and you'll understand the structure pretty easily.

You'll read the comments for "version 1" and "version 2" and you'll be able to comment the one and try the other, to confirm both cases.

**Comment by andrey-zherikov** [comment]
### Version1
You missed few imports and returns:
```diff
diff --git a/source/app.d b/source/app.d
index f49c6ef..4f9ace8 100644
--- a/source/app.d
+++ b/source/app.d
@@ -1,6 +1,7 @@
 import argparse;

 import std.stdio;
+import std.sumtype;

 import help;
 import build;
@@ -15,14 +16,17 @@ mixin CLI!CmdData.main!((prog) {
   int result = prog.cmd.match!(
     (.HelpMode) {
       writeln("This is the help mode!");
+         return 0;
     },

     (.BuildMode) {
       writeln("This is the build mode!");
+         return 0;
     },

     (.RunMode) {
       writeln("This is the run mode!");
+         return 0;
     }
   );

diff --git a/source/cmd_data.d b/source/cmd_data.d
index 2be6b03..e63b603 100644
--- a/source/cmd_data.d
+++ b/source/cmd_data.d
@@ -1,3 +1,8 @@
+import std.sumtype;
+import help;
+import build;
+import run;
+
 struct CmdData {
   SumType!(HelpMode, RunMode, BuildMode) cmd;
 }

```

### Version 2
You missed same imports:
```diff
diff --git a/source/cmd_data.d b/source/cmd_data.d
index 2be6b03..e63b603 100644
--- a/source/cmd_data.d
+++ b/source/cmd_data.d
@@ -1,3 +1,8 @@
+import std.sumtype;
+import help;
+import build;
+import run;
+
 struct CmdData {
   SumType!(HelpMode, RunMode, BuildMode) cmd;
 }

```

**Comment by rempas** [comment]
Ok, I have good news and bad news.

Good news is that it works!

Bad news:

1. I didn't know "sumtype" is from D :facepalm:! Sorry about that!
2. While it works in the *example* package, it doesn't work in the real source code ( :facepalm: again).

Thanks so much for the help you gave me. If you want to help further, I have updated the source code to add the real source code. The **SOURCE_WORKING** directory contains the fixed example that compiles. **source** contains that real source code that does not compile. The error message (which you'll probably see, but I'm posting anyway) is:

```
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(150,45): Error: template instance `parseArgs!(__lambda5)` does not match any template declaration
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(150,45):        Candidates are:
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(65,16):        parseArgs(alias newMain)(string[] args, COMMAND initialValue = COMMAND.init) if (__traits(compiles, ()
{
newMain(COMMAND.init);
}
))
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(83,16):        parseArgs(alias newMain)(string[] args, COMMAND initialValue = COMMAND.init) if (__traits(compiles, ()
{
newMain(COMMAND.init, string[].init);
}
))
source/app.d(13,1):        parent scope from here: `mixin main!((prog)
{
static assert(is(typeof(prog) == CmdData));
int result = prog.cmd.match!((.HelpMode)
{
writeln("This is the help mode!");
return 0;
}
, (.BuildMode)
{
writeln("This is the build mode!");
return 0;
}
, (.RunMode)
{
writeln("This is the run mode!");
return 0;
}
);
writeln("result = ", result);
return 0;
}
)`
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(150,45): Error: template instance `parseArgs!(__lambda5)` does not match any template declaration
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(150,45):        Candidates are:
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(65,16):        parseArgs(alias newMain)(string[] args, COMMAND initialValue = COMMAND.init) if (__traits(compiles, ()
{
newMain(COMMAND.init);
}
))
../../../../.dub/packages/argparse/1.3.0/argparse/source/argparse/api/cli.d(83,16):        parseArgs(alias newMain)(string[] args, COMMAND initialValue = COMMAND.init) if (__traits(compiles, ()
{
newMain(COMMAND.init, string[].init);
}
))
source/cmd_args/parse_cmd_args.d(36,1):        parent scope from here: `mixin main!((prog)
{
static assert(is(typeof(prog) == CmdData));
int result = prog.cmd.match!((.HelpMode)
{
writeln("This is the help mode!");
}
, (.BuildMode)
{
writeln("This is the build mode!");
}
, (.RunMode)
{
writeln("This is the run mode!");
}
);
writeln("result = ", result);
return 0;
}
)`
```

P.S. Sorry for the wasted time. I'll make it up to you and everyone else with the language I'm building ;)

**Comment by andrey-zherikov** [comment]
These errors mean that a function which you pass to `CLI.main` is not compilable. I suggest trying to call it with `CmdData.init` object directly (like in unit test).
Looking at [parse_cmd_args.d](https://codeberg.org/rempas/trying_argparse/src/branch/master/source/cmd_args/parse_cmd_args.d) I spotted that functions you pass to `match` doesn't return anything but you assign the result of `match` to `int result`. Also there is no `import std.sumtype` that imports `match` in that file.

**Comment by rempas** [comment]
> Looking at [parse_cmd_args.d](https://codeberg.org/rempas/trying_argparse/src/branch/master/source/cmd_args/parse_cmd_args.d) I spotted that functions you pass to `match` doesn't return anything but you assign the result of `match` to `int result`. Also there is no `import std.sumtype` that imports `match` in that file.

Other than not knowing that, [parse_cmd_args.d](https://codeberg.org/rempas/trying_argparse/src/branch/master/source/cmd_args/parse_cmd_args.d) should not exist as at all as, both this and [app.d](https://codeberg.org/rempas/trying_argparse/src/branch/master/source/app.d) have the main function (and `app.d` has the returns, as it should) and I forgot that... :facepalm:

> These errors mean that a function which you pass to `CLI.main` is not compilable. I suggest trying to call it with `CmdData.init` object directly (like in unit test).

No problem. Now that I removed [parse_cmd_args.d](https://codeberg.org/rempas/trying_argparse/src/branch/master/source/cmd_args/parse_cmd_args.d), it works without problems at last!

Thank you so much for your time, and I'm so sorry, as I could have probably fixed all those problems myself if I knew more of D (`std.sumtype`) and I was not posting at night, so I wouldn't miss code duplications and returns that aren't there.

Have a beautiful day or night! :heart:
