### ISSUE TITLE
Make it possible to use non compile time data for epilogs?

### ISSUE THREAD

**Issue by gizmomogwai** [andrey-zherikov/argparse#45]
I would like to show some information in the epilog, that is not available as compile time constant.

**Comment by andrey-zherikov** [comment]
It shouldn't be a big problem. I think accepting `string delegate()` would be good enough for this (it should be called when help is printed).

**Comment by gizmomogwai** [comment]
sounds very good for my usecase!

**Comment by gizmomogwai** [comment]
Thanks a lot!
Works great for my usecase!
Seems like this will trigger a new version (probably major) for your next release, as the api is incompatible to the old one?

**Comment by andrey-zherikov** [comment]
> Seems like this will trigger a new version (probably major) for your next release, as the api is incompatible to the old one?

Why is in incompatible? You can still do `Epilog("some string")`

**Comment by gizmomogwai** [comment]
ah ok .. i only looked at the diff and there only the delegate was used ... but then its an even greater feature :)
