### ISSUE TITLE
In some of my projects I get a cryptic compile error

### ISSUE THREAD

**Issue by gizmomogwai** [andrey-zherikov/argparse#66]
Happens only with some versions of the compiler e.g dmd-2.100.0.
``
`
../../external/argparse/source/argparse/package.d(425,6): Error: typesafe variadic function parameter `name` of type `string[]` cannot be marked `return`
```

**Comment by gizmomogwai** [comment]
my local version of argparse is pointing to `master`

**Comment by gizmomogwai** [comment]
mhh .. somehow dub pulls -dip1000 in :/ seems to be my mistake then!

**Comment by andrey-zherikov** [comment]
I do get dmd errors from time to time. For example, I recently got "illegal instruction" inside dmd with my local change.
That's why every commit to master is verified: https://github.com/andrey-zherikov/argparse/runs/7848427132?check_suite_focus=true

**Comment by andrey-zherikov** [comment]
> mhh .. somehow dub pulls -dip1000 in :/ seems to be my mistake then!

Does this mean that there is no issue?

**Comment by gizmomogwai** [comment]
Not sure yet ... it behaves better, when I remove the dip1000 switch, but the question is, if argparse should already look forward to dip1000 ... will test a little more.

**Comment by gizmomogwai** [comment]
yes ... I tested again, and with dmd-2.100.0 and the addition ` "dflags": ["-dip1000"]` to argparse's dub.json I get exactly the described error. So it was a dub dependency of mine, that declared ´-dip1000` which got promoted to my main application that uses argparse ... so i think we can close this issue or rename it to something like "support dip1000"

**Comment by ljmf00-wekaio** [comment]
Hey, I got this issue today when porting to latest LDC 1.30.0.

It seems that the code is violating some DIP1000 rules, because typesafe variadic function parameters can live on the stack, and therefore need to either use `.dup`, or know the length at compile-time instead of relying on a possible stack allocation or mark it as `scope` if you are sure this won't escape. The main reason for this to happen is that returning `auto` make the compiler infer attributes.

I believe the `.dup` option is fine here, since `NamedArgument` is used as an UDA and therefore the value is CTFEable, not leading to a GC allocation after-all.

The following patch fixes this and another other DIP1000 issue:

```diff
diff --git a/source/argparse/internal.d b/source/argparse/internal.d
index 50117d0..54112bf 100644
--- a/source/argparse/internal.d
+++ b/source/argparse/internal.d
@@ -617,7 +617,7 @@ package alias ParsingArgument(alias symbol, alias uda, ArgumentInfo info, RECEIV
         }
     };
 
-package auto ParsingSubCommandArgument(COMMAND_TYPE, CommandInfo info, RECEIVER, alias symbol, bool completionMode)(const CommandArguments!RECEIVER* parentArguments)
+package auto ParsingSubCommandArgument(COMMAND_TYPE, CommandInfo info, RECEIVER, alias symbol, bool completionMode)(const scope CommandArguments!RECEIVER* parentArguments)
 {
     return delegate(Config* config, ref Parser parser, const ref Parser.Argument arg, bool isDefaultCmd, ref RECEIVER receiver)
     {
diff --git a/source/argparse/package.d b/source/argparse/package.d
index ae32332..ac885e0 100644
--- a/source/argparse/package.d
+++ b/source/argparse/package.d
@@ -424,7 +424,7 @@ auto PositionalArgument(uint pos, string name)
 
 auto NamedArgument(string[] name...)
 {
-    return ArgumentUDA!(ValueParseFunctions!(void, void, void, void, void, void))(ArgumentInfo(name)).Optional();
+    return ArgumentUDA!(ValueParseFunctions!(void, void, void, void, void, void))(ArgumentInfo(name.dup)).Optional();
 }
 
 auto NamedArgument(string name)
@@ -1751,4 +1751,4 @@ unittest
     assert(test("auto")   == Config.StylingMode.autodetect);
     assert(test("never")  == Config.StylingMode.off);
     assert(test("")       == Config.StylingMode.autodetect);
-}
\ No newline at end of file
+}
```

**Comment by andrey-zherikov** [comment]
Thanks for diving into this! I'll take a look once I'm done with current work
