### ISSUE TITLE
Shell Completion Generation

### ISSUE THREAD

**Issue by nordlow** [andrey-zherikov/argparse#7]
Would be awesome to have a flag that outputs shell completion code primarily for bash and zshell.

Python has this at https://kislyuk.github.io/argcomplete/.

**Comment by andrey-zherikov** [comment]
I started looking at this.

**Comment by gizmomogwai** [comment]
Thanks a lot in advance!

**Comment by andrey-zherikov** [comment]
I did some research (shell completion is something new to me) and I got an idea how this can be done. Implementation requires some refactoring tho and this is what I'm gonna work on next.

**Comment by andrey-zherikov** [comment]
The implementation would work for bash, zsh, tcsh (with some limitation) and fish.
