### ISSUE TITLE
Name of Positional Argument is ignored?

### ISSUE THREAD

**Issue by linkrope** [andrey-zherikov/argparse#70]
```
mixin CLI!Params.main!((arguments) { });

struct Params
{
    @PositionalArgument(0, "bar")
    string foo;
}
```
shows the help as
```
Usage: command [-h] foo

Required arguments:
  foo
```
while I would have expected "bar" instead of "foo" from the README.
(Especially in the case that the CLI parameter is a keyword of D.)

**Comment by andrey-zherikov** [comment]
Thanks for pointing this out, I'll fix it. Technically positional argument doesn't have a name (something like `--foo`) - it has only value which is `placeholder`.

**Comment by linkrope** [comment]
Now that I know, I like the Placeholder even more.
