### ISSUE TITLE
Affect usage description for a main program?

### ISSUE THREAD

**Issue by schveiguy** [andrey-zherikov/argparse#74]
For a subcommand, you can affect the description by attributing the command with information.

But I want to just add a description for the whole program. Is that possible to do?

**Comment by andrey-zherikov** [comment]
Did you try `Command` attribute?
```d
@(Command.Description("Description for the whole program"))
struct MainProgram
{
...
}
```

**Comment by schveiguy** [comment]
Does that work? Because I thought Command required a parameter of the program name. I tried `Command().Description(...)` and it failed to compile.

I'll check when I get a chance.

**Comment by schveiguy** [comment]
To be clearer, I want to use the automatic mechanism that detects the program name (I'm assuming from argv[0]) and uses that for the usage, but still provides a nice description.

My current implementation uses `Command("foo").Description(...)` and it works, where "foo" is the program name. This is OK if there is no other way, but I would prefer to be more DRY.

**Comment by andrey-zherikov** [comment]
It should work - if you don't specify command name then it's gonna use `argv[0]`. Let me know if it does not.

**Comment by andrey-zherikov** [comment]
I just checked with one of the examples - compilation failed. I'll fix it.

**Comment by andrey-zherikov** [comment]
@schveiguy I added this to [example](https://github.com/andrey-zherikov/argparse/blob/master/examples/sub_commands/advanced/app.d#L58):
```d
@(Command.Description("Description of main program"))
struct Program
{
...
}
```

**Comment by schveiguy** [comment]
Thanks!
