### ISSUE TITLE
Positional arguments do not ignore executable itself on Windows

### ISSUE THREAD

**Issue by vladimmi** [andrey-zherikov/argparse#87]
It seems, `PositionalArgument(0)` actually gets the name of the executable itself, at least on Windows. I have struct defined this way:

```d
@(Command.Description("Simple tool that generates a D source module embedding specified resources into it"))
struct Options {
    @(
        PositionalArgument(0)
            .Description("Resource manifest to process")
    )
    string manifest;

    @(
        NamedArgument("d", "developer")
            .Description("Read resources from filesystem instead of actually embedding them")
    )
    bool developerMode = false;
}
```

Argument parsing is called this way:

```d
void main(string[] args) {
    CLI!Options.parseArgs!typedMain(args);
}
```

And for the test I just output the parsed `manifest` option:

```d
void typedMain(Options args) {
    info("Provided manifest file: " ~ args.manifest);
}
```

Seems to follow examples from docs, if I'm not missing something obvious... Well, results:

```
> embed-resources
Provided manifest file: embed-resources

> embed-resources manifest.json
Error: Unrecognized arguments: ["manifest.json"]
```

**Comment by andrey-zherikov** [comment]
This thing needs to be clarified in readme. `parseArgs` requires args without arg0 as you can see [here](https://github.com/andrey-zherikov/argparse/blob/master/source/argparse/package.d#L831):
```d
int main(string[] argv)
{
    return CLI!(config, COMMAND).parseArgs!(newMain)(argv[1..$]);
}
```

**Comment by vladimmi** [comment]
Yep, that's what I did after all. And now that you mentioned it, I've found it's actually written in readme:
https://github.com/andrey-zherikov/argparse/blob/ddfbfee9ec0363d512ae1bd325ffdf0fff2918a0/README.md?plain=1#L398
But this example made me think it's handled by library internally:
https://github.com/andrey-zherikov/argparse/blob/ddfbfee9ec0363d512ae1bd325ffdf0fff2918a0/README.md?plain=1#L373

**Comment by andrey-zherikov** [comment]
@vladimmi Could you please take a look at #92 whether it's clear now?

**Comment by vladimmi** [comment]
Yes, looks great for me, now all examples with custom main function have correct slice.

**Comment by andrey-zherikov** [comment]
Thank you a lot!
